version: '3.8'

services:
  mysql:
    image: mysql/mysql-server:8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cooldatabase
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    command: ['--default-authentication-plugin=mysql_native_password', '--ssl=0']
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    networks:
      - backend

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: cooldatabase
    ports:
      - "27017:27017"
    command: ["--auth"]
    volumes:
      - mongo-data:/data/db
    restart: always
    networks:
      - backend

volumes:
  mysql-data:
  mongo-data:

networks:
  backend:
