# WorldwideChat Configuration
#       _    _            _     _          _     _      _____ _           _   
#      | |  | |          | |   | |        (_)   | |    /  __ \ |         | |  
#      | |  | | ___  _ __| | __| |_      ___  __| | ___| /  \/ |__   __ _| |_ 
#      | |/\| |/ _ \| '__| |/ _` \ \ /\ / / |/ _` |/ _ \ |   | '_ \ / _` | __|    - by 3xpl0itz
#      \  /\  / (_) | |  | | (_| |\ V  V /| | (_| |  __/ \__/\ | | | (_| | |_ 
#       \/  \/ \___/|_|  |_|\__,_| \_/\_/ |_|\__,_|\___|\____/_| |_|\__,_|\__|
#
# HOW TO SETUP: https://github.com/3xpl0itz/WorldwideChat/wiki/Default-Explained-config.yml
#
General:
  prefixName: WWC
  enablebStats: true
  pluginLang: en
  updateCheckerDelay: 86400
  syncUserDataDelay: 7200
  enableDebugMode: false
Storage:
  useSQL: false
  sqlHostname: localhost
  sqlPort: 3306
  sqlDatabaseName: cooldatabase
  sqlUsername: root
  sqlPassword: root
  sqlUseSSL: false
Chat:
  sendTranslationChat: true
  sendFailedTranslationChat: true
  sendPluginUpdateChat: true
  sendIncomingHoverTextChat: true
Translator:
  useWatsonTranslate: true
  watsonAPIKey: watson_key_goes_here
  watsonURL: watson_site_goes_here
  useGoogleTranslate: false
  googleTranslateAPIKey: google_translate_key_goes_here
  useAmazonTranslate: false
  amazonAccessKey: amazon_translate_key_goes_here
  amazonSecretKey: amazon_translate_secret_goes_here
  amazonRegion: amazon_region_goes_here
  translatorCacheSize: 100
  rateLimit: 0
  messageCharLimit: 255
  errorLimit: 5
