name: WorldwideChat
version: 1.4
description: Break the blocky language barrier!
api-version: 1.14
author: 3xpl0itz
main: com.expl0itz.worldwidechat.WorldwideChat
commands:
    wwc:
        description: Prints WorldwideChat version.
        aliases: [worldwidechat]
        usage: §4/wwc
        permission: worldwidechat.wwc
        permission-message: §4You do not have permission to run this command.
    wwcr:
        description: Reloads WorldwideChat.
        aliases: [wwcreload, translatereload]
        usage: §4/wwcr
        permission: worldwidechat.wwcr
        permission-message: §4You do not have permission to run this command.
    wwcg:
        description: Enables chat translation to a certain language globally.
        aliases: [wwcglobal, gtranslate]
        usage: §4/wwcg (language-in) (language-out)
        permission: worldwidechat.wwcg
        permission-message: §4You do not have permission to run this command.
    wwct:
        description: Enables chat translation to a certain language, either for you or a specific player.
        aliases: [wwctranslate, translate]
        usage: §4/wwct (playerName) (language-in) (language-out)
        permission: worldwidechat.wwct
        permission-message: §4You do not have permission to run this command.
    wwctb:
        description: Enables book translation to a certain language.
        aliases: [wwctranslatebook, translatebook]
        usage: §4/wwctb (playerName)
        permission: worldwidechat.wwctb
        permission-message: §4You do not have permission to run this command.
    wwcts:
        description: Enables sign translation to a certain language.
        aliases: [wwctranslatesign, translatesign]
        usage: §4/wwcts (playerName)
        permission: worldwidechat.wwcts
        permission-message: §4You do not have permission to run this command.
    wwcti:
        description: Enables item translation to a certain language.
        aliases: [wwctranslateitem, translateitem]
        usage: §4/wwcti (playerName)
        permission: worldwidechat.wwcti
        permission-message: §4You do not have permission to run this command.
    wwcs:
        description: Gets translation stats for a specified user.
        aliases: [wwctranslatestats, translatestats]
        usage: §4/wwcs (playerName)
        permission: worldwidechat.wwcs
        permission-message: §4You do not have permission to run this command.
    wwcc:
        description: Opens the Configuration GUI for the command sender.
        aliases: [wwcconfiguration, translateconfiguration]
        usage: §4/wwcc
        permission: worldwidechat.wwcc
        permission-message: §4You do not have permission to run this command.
    wwcrl:
        description: Sets a rate limit for the specified user.
        aliases: [wwcratelimit, translateratelimit]
        usage: §4/wwcrl (delay) or /wwcrl (playerName) (delay)
        permission: worldwidechat.wwcrl
        permission-message: §4You do not have permission to run this command.
permissions:
    worldwidechat.*:
        description: Gives access to all WorldwideChat commands.
        children:
            worldwidechat.wwc: true
            worldwidechat.wwcr: true
            worldwidechat.wwcg: true
            worldwidechat.wwct: true
            worldwidechat.wwct.otherplayers: true
            worldwidechat.chatupdate: true
            worldwidechat.wwctb: true
            worldwidechat.wwctb.otherplayers: true
            worldwidechat.wwcts: true
            worldwidechat.wwcts.otherplayers: true
            worldwidechat.wwcti: true
            worldwidechat.wwcti.otherplayers: true
            worldwidechat.wwcs: true
            worldwidechat.ratelimit.exempt: true
            worldwidechat.wwcc: true
            worldwidechat.wwcrl: true
        default: op
    worldwidechat.wwc:
        description: Gives access to /wwc.
        default: true
    worldwidechat.wwcr:
        description: Gives access to /wwcr.
        default: op
    worldwidechat.wwcg:
        description: Gives access to /wwcg.
        default: op
    worldwidechat.wwct:
        description: Gives access to /wwct.
        default: true
    worldwidechat.wwct.otherplayers:
        description: Gives access to /wwct to a certain language for other players.
        default: op
    worldwidechat.chatupdate:
        description: Gives access to receiving of plugin update notification in chat on login.
        default: op
    worldwidechat.wwctb:
        description: Gives access to /wwctb.
        default: true
    worldwidechat.wwctb.otherplayers:
        description: Gives access to /wwctb to a certain language on target players.
        default: op
    worldwidechat.wwcts:
        description: Gives access to /wwcts.
        default: true
    worldwidechat.wwcts.otherplayers:
        description: Gives access to /wwcts to a certain language on target players.
        default: op
    worldwidechat.wwcti:
        description: Gives access to /wwcti.
        default: true
    worldwidechat.wwcti.otherplayers:
        description: Gives access to /wwcti to a certain language on target players.
        default: op
    worldwidechat.wwcs:
        description: Gives access to /wwcs.
        default: op
    worldwidechat.ratelimit.exempt:
        description: Exempts a user from rate limits, both personally and globally.
        default: op
    worldwidechat.wwcc:
        description: Gives access to /wwcc.
        default: op
    worldwidechat.wwcrl:
        description: Gives access to /wwcrl.
        default: op
