# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Bleeding-Edge Builds (Development Branch)

on:
  push:
    branches: [ development-1.x ]
  pull_request:
    branches: [ development-1.x ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: 17
       
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Upload final artifact
      run: mkdir staging && cp target/WorldwideChat.jar staging/WorldwideChat.jar
    - uses: actions/upload-artifact@v3
      with:
        name: WorldwideChat Jar
        path: staging
